#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'shaderapidx11'

def options(opt):
	# stub
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'SHADERAPIDX11',
		'SHADER_DLL_EXPORT',
		'USE_ACTUAL_DX',
		'strncpy=use_Q_strncpy_instead',
		'_snprintf=use_Q_snprintf_instead',
	])

def build(bld):
	source = [
		'shaderapidx11_stub.cpp',
		'shaderdevicedx11.cpp',
		'shadermanagerdx11.cpp',
		'statedx11.cpp',
		'texturedx11.cpp',
		'meshdx11.cpp',
		'blitdx11.cpp',
		'../shaderapidx9/meshbase.cpp',
		# API-clean base TUs shared with the DX9 module (see Plan.md)
		'../shaderapidx9/shaderdevicebase.cpp',
		'../shaderapidx9/shaderapibase.cpp',
		'../shaderapidx9/hardwareconfig.cpp',
		'../../public/filesystem_helpers.cpp',
		'../../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../shaderapidx9',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common',
		'../'
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = ['tier0','tier1','tier2','vstdlib','bitmap','mathlib']

	if bld.env.DEST_OS == 'win32':
		libs += ['D3D11', 'DXGI', 'D3DCOMPILER', 'DXGUID', 'USER32']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
