#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'client'

tf_excluded_source_suffixes = [
	'game/shared/mapbase/vscript_funcs_hl2.cpp'
]

def is_tf_excluded_source(path):
	path = path.replace('\\', '/').lower()
	return any(path.endswith(suffix) for suffix in tf_excluded_source_suffixes)

def options(opt):
	return

games = {
	'hl2': ['client_base.vpc', 'client_hl2.vpc', 'imgui/imgui_system.vpc'],
	'hl2mp': ['client_base.vpc', 'client_hl2mp.vpc', 'imgui/imgui_system.vpc'],
	'hl1': ['client_base.vpc', 'client_hl1.vpc', 'imgui/imgui_system.vpc'],
	'episodic': ['client_base.vpc', 'client_episodic.vpc', 'imgui/imgui_system.vpc'],
	'portal': ['client_base.vpc', 'client_portal.vpc', 'imgui/imgui_system.vpc'],
	'hl1mp': ['client_base.vpc', 'client_hl1mp.vpc', 'imgui/imgui_system.vpc'],
	'cstrike': ['client_base.vpc', 'client_cstrike.vpc', 'imgui/imgui_system.vpc'],
	'dod': ['client_base.vpc', 'client_dod.vpc', 'imgui/imgui_system.vpc'],
	'tf': [
		'client_base.vpc',
		'client_econ_base.vpc',
		'client_tf.vpc',
		'imgui/imgui_system.vpc'
	]
}

def configure(conf):
	game = conf.options.GAMES
	conf.env.GAMES = game

	conf.env.append_unique('DEFINES', ['DISABLE_STEAM=1'])
	if game == 'tf':
		conf.env.append_unique('DEFINES', ['SOURCESDK=1', 'TF'])

	if game not in games.keys():
		conf.fatal("Couldn't find game: ", game)

def build(bld):
	game = vpc_parser.parse_vpcs( bld.env, games[bld.env.GAMES], '../..' )

	includes = [
		'.',
		'game_controls',
		'../../common',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../vgui2/include',
		'../../vgui2/controls',
		'../shared'
	]

	linkflags = []

	libs = [
		'tier0',
		'particles',
		'dmxloader',
		'vgui_controls',
		'matsys_controls',
		'tier1',
		'tier2',
		'tier3',
		'mathlib',
		'vstdlib',
		'choreoobjects',
		'steam_api',
		'bitmap',
		'vtf',
		'vscript',
		'RT',
		'ZLIB'
	]

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android':
		install_path += '/'+bld.env.GAMES+'/bin'

	source = [
		'in_touch.cpp',
		# util_shared.cpp's UTIL_SteamIDFromProperString needs the CSteamID
		# string helpers in every game, not just tf (hl2 client link fix)
		'../../common/steamid.cpp',
	]
	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	if bld.env.GAMES == 'tf':
		includes += [
			'../..',
			'../../gcsdk',
			'../../gcsdk/steamextra',
			'../../public/gcsdk',
			'../../thirdparty/JSON_parser',
			'generated_proto_tf',
			'../../thirdparty/protobuf-2.6.1/src'
		]
		libs += ['PNG', 'JPEG']
		if bld.env.DEST_OS == 'win32':
			libs += ['GDI32']
		source += [
			'../../gcsdk/gcclient.cpp',
			'../../gcsdk/gcclient_sharedobjectcache.cpp',
			'../../gcsdk/gcconstants.cpp',
			'../../gcsdk/gclogger.cpp',
			'../../gcsdk/gcmsg.cpp',
			'../../gcsdk/job.cpp',
			'../../gcsdk/jobmgr.cpp',
			'../../gcsdk/jobtime.cpp',
			'../../gcsdk/messagelist.cpp',
			'../../gcsdk/msgprotobuf.cpp',
			'../../gcsdk/netpacket.cpp',
			'../../gcsdk/netpacketpool.cpp',
			'../../gcsdk/protobufsharedobject.cpp',
			'../../gcsdk/sharedobject.cpp',
			'../../gcsdk/sharedobjectcache.cpp',
			'../../gcsdk/steamextra/misc.cpp',
			'../../gcsdk/steamextra/rtime.cpp',
			'../../gcsdk/steamextra/tier1/hashglobals.cpp',
			'../../gcsdk/steamextra/tier1/tsmempool.cpp',
			'../../gcsdk/steamextra/tier1/tsmultimempool.cpp',
			'../../gcsdk/webapi_response.cpp',
			'../../gcsdk/workthreadpool.cpp',
			'../../game/shared/tf/tf_gcmessages.cpp',
			'../../thirdparty/JSON_parser/JSON_parser.c',
			'generated_proto_tf/steammessages.pb.cc',
			'generated_proto_tf/gcsystemmsgs.pb.cc',
			'generated_proto_tf/gcsdk_gcmessages.pb.cc',
			'generated_proto_tf/base_gcmessages.pb.cc',
			'generated_proto_tf/econ_gcmessages.pb.cc',
			'generated_proto_tf/tf_gcmessages.pb.cc',
			'generated_proto_tf/tf_proto_def_messages.pb.cc'
		]
		if bld.env.DEST_OS == 'win32':
			protobuf_lib_path = os.path.abspath(os.path.join(bld.path.abspath(), '../../thirdparty/protobuf-2.6.1/bin/win64/2015/staticcrt/release'))
			linkflags += ['/LIBPATH:' + protobuf_lib_path, 'libprotobuf.lib', 'winmm.lib']

	source += game["sources"] + ['../../public/tier0/memoverride.cpp']
	if bld.env.GAMES == 'tf':
		source = [s for s in source if not is_tf_excluded_source(s)]
	includes += game["includes"]
	defines = game["defines"]

	defines.remove('PROTECTED_THINGS_ENABLE')

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		linkflags = linkflags,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

