#! /usr/bin/env python
# encoding: utf-8
# hammer.exe: thin appframework loader for hammer_dll (hammer_launcher.vpc)

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hammer'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'main.cpp',
		'hammer_launcher.rc'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	defines = []

	libs = [
		'tier0', 'tier1', 'vstdlib', 'appframework',
		'USER32', 'SHELL32'
	]

	install_path = bld.env.LIBDIR

	bld.program(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		cxxflags = ['/EHa'],
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
